Feat/delete-cylinder-set
Tampereen-Urheilusukeltajat/Blenderi-Backend pull request #26
Opened 2022-10-22 13:15 UTC by Tiikewi

Pullo setin ja sen yksittäisen pullojen poisto

2022-10-23 08:15 UTC, Akzuu commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +    }
Tän looppaamisen pitäis kyetä tekemään SQL kannan sisällä asettamalla where ehtoon useamman ID:n

2022-10-23 08:15 UTC, Akzuu commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  tags: ['Cylinder set', 'Delete'],
Ile ei tykkää siitä että noita endpointteja tagataan tyypin mukaan (Delete, Post, jne)

2022-10-23 08:15 UTC, Akzuu commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +    }
https://knexjs.org/guide/query-builder.html#wherein

2022-10-23 08:15 UTC, Akzuu commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +      .where('cylinder_set', setId);
Heti tän kyselyn jälkeen voidaan jo päätellä 404

2022-10-23 09:12 UTC, ilesoft commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  tags: ['Cylinder set', 'Delete'],
En niin. Itse ainakin käytän ja testaan tätä apia swaggerin kautta ja tuollainen tuplatagi lisää tän endpointin sinne dokumentaatioon kahdesti. Toisekseen swagger liputtaa tän deleten punaisella joka tapauksessa.

2022-10-23 09:27 UTC, ilesoft commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  tags: ['Cylinder set', 'Delete'],
![image](https://user-images.githubusercontent.com/45848534/197384536-89e7cfc3-4e45-4d58-bb09-98ff2d709a06.png)
Tähän tapaan

2022-10-23 09:34 UTC, ilesoft commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  response: {
Tää voi lisäksi olla ainakin 400, 401 tai 403

2022-10-23 19:10 UTC, ilesoft commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +  test('it responses 400 when no set with given id', async () => {
```suggestion
  test('it responses 404 when no set with given id', async () => {
```

2022-10-23 19:10 UTC, ilesoft commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +  });
Täähän ei sinänsä testaa tätä endpointtia vaan sitä ettei DELETE /api/cylinder-set -endpointtia ole olemassa. Ei tästä kyllä mitään haittaakaan ole :D

2022-10-24 07:16 UTC, toppeh requested changes

2022-10-24 07:16 UTC, toppeh commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  });
Voisiko tämän transaction siirtää /lib/ kansioon? Helpottaisi minun elämää, jos (ja varmaan kun) DELETE userissa täytyy poistaa myös cylinder settejä

2022-10-24 12:38 UTC, Akzuu commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  });
Helvetti, ei olla muistettu tehdä noita foreign_key:tä `ON DELETE CASCADE`  optiolla. Täytyy korjata

2022-10-24 12:54 UTC, Akzuu approved these changes
Hyvin kommentoitu. Toiminnallisuus riittää MVP:tä varten

2022-10-24 17:35 UTC, ilesoft approved these changes
Toimii

2022-10-24 17:35 UTC, ilesoft commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  // Delete culinder set.
```suggestion
  // Delete cylinder set.
```

2022-10-24 17:35 UTC, ilesoft commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  // Delete culinder set.
Meinas päätyä iltateet näppäimistölle 😄

2022-10-24 17:35 UTC, ilesoft commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +    // Before delete, there was 3 sets.
```suggestion
    // Before delete, there were 3 sets.
```

2022-10-24 17:42 UTC, ilesoft commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +    // Bedofre delete there is 4 cylinders and 2 should be deleted.
```suggestion
    // Before delete there is 4 cylinders and 2 should be deleted.
```

2022-10-24 18:47 UTC, toppeh commented on src/lib/deleteCylinderSet.ts
> +    return { status: 200, message: 'set deleted successfully.' };
message: 'Set deleted successfully.'

2022-10-24 18:56 UTC, toppeh approved these changes

2022-10-24 18:56 UTC, toppeh commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +    const cylinderID = 'f4e1035e-f36e-4056-9a1b-5925a3c5793e';
const cylinderSetId

2022-10-24 18:56 UTC, toppeh commented on src/test/routes/cylinder-set/deleteCylinderSet.test.ts
> +    const cylinderID = 'f4e1035e-f36e-4056-9a1b-5925a3c5793e';
```suggestion
    const cylinderSetID = 'f4e1035e-f36e-4056-9a1b-5925a3c5793e';
```

2022-10-24 18:56 UTC, toppeh commented on src/lib/deleteCylinderSet.ts
> +    return { status: 200, message: 'set deleted successfully.' };
```suggestion
    return { status: 200, message: 'Set deleted successfully.' };
```

2022-10-24 19:09 UTC, Tiikewi commented on src/routes/cylinder-set/deleteCylinderSet.ts
> +  // Delete culinder set.
😁 Tää aiheutti kyllä ihan liikaa huvitusta. Culinder

2022-10-24 19:19 UTC, merged