Db/fill event
Tampereen-Urheilusukeltajat/Blenderi-Backend pull request #28
Opened 2022-10-25 17:47 UTC by toppeh

2022-10-25 17:48 UTC, toppeh commented
Onko 2048 riittävän iso taikaluku lisäinfo kohtaan?

2022-10-26 18:54 UTC, ilesoft requested changes

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.dropTable('fill_event');
```suggestion
  await knex.schema.dropTableIfExists('fill_cylinder_event');
  await knex.schema.dropTableIfExists('fill_event');
```
Tästä ei varmaan olis haittaa.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.createTable('fill_cylinder_event', (table) => {
Tän pitäisi olla varmaan 
```suggestion
  await knex.schema.createTable('fill_cylinder_set_event', (table) => {
```
Käsittääkseni ne välisillalliset tuplapullot ainakin täytetään yhtaikaa

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
```suggestion
      .checkIn(['air', 'oxygen', 'helium', 'argon'])
```
Ja jos halutaan käyttää jotain muuta termiä kuin  `air` niin sitten varmaan `compressed_air`

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
Jaaa tälläinen rakennehan kuuluisi kait olla enum ([doc](https://mariadb.com/kb/en/enum/) ja [doc](https://knexjs.org/guide/schema-builder.html#enum-enu)). Muistaen että pitää tarkistaa sql_mode == strict ettei dataintegriteetti vaarannu tyhjistä enum-arvoista.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
Ja noita kaasujahan on siinä pullotäytössä aina jokin osapaine, tälläinen sarake antaisi täyttää vain yhtä kaasua pulloon. Todellisuudessa pullosettiin päätyy jotain seuraavista kaasuseoksista:
* ilma
* nitrox
* trimix
* heliox
* argon
* lista varmaan jatkuu

Se että halutaanko tämä tieto tälläisenään kantaan on toinen kysymys.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
Jos ja kun halutaan tallentaa tieto siitä mitä kaasuja täytössä on käytetty ja kuinka paljon niin tätä ongelmaa pitää lähestyä jotenkin toisin.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
Yksi vaihtoehto olisi varmaa se, että käytettäville kaasuille (ilma, happi, helium, argon, diluentti) olisi jokaiselle oma sarakkeensa johon arvoksi tulisi osapaine bareina. Tai sitten kirjataan maksullisten kaasujen osalta paljonko minkäkin varastopullon paine on laskenut (tämä muodostaa täytön hinnan). Tai sitten käyttöliittymässä on erikseen kentät varastopullojen paineille ja tämän taulun hintasarakkeen arvo lasketaan niistä?. Tai sekä että. En tiedä. En ole (vielä) kaasunsekoituksen asiantuntija.

Harmi että asiantuntijamme on lomalla, meille luvatut speksit jumissa bittiavaruudessa ja tiukempien kaasuseoksien kirjaamiseen käytetyn taulukon kuvat ottamatta.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +    table.integer('fill_pressure').unsigned().notNullable();
Jos tässä taulussa on jokin tälläinen painetta kuvaava sarake niin tuo `fill_` on turha prefiksi.

2022-10-26 18:54 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +    table.integer('cost').unsigned().notNullable(); // cost in euro cents
```suggestion
    table.integer('price').unsigned().notNullable(); // price in euro cents
```
Ehkä

2022-10-26 18:59 UTC, ilesoft commented
> Onko 2048 riittävän iso taikaluku lisäinfo kohtaan?

Luulis vaikka 400 merkkiä olevan riittävä. Tänne pitäisi kait tulla vain pieniä huomioita. Isomman huomion sattuessa sen voi tilittää vaikka seuran kaasuvastaavalle tai hätäkeskukselle.

2022-10-26 19:06 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.createTable('fill_cylinder_event', (table) => {
Sit jos käyttäjällä on tuplasetti ilman välisiltaa (en tiedä onko tälläisiä olemassa) ja niihin meneekin eri kamaa niin auta armias en tiedä mitä meidän pitäisi tehdä.

2022-10-26 20:30 UTC, toppeh commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.dropTable('fill_event');
Periaattessa turha, mutta ei siitä varmaan haittaakaan ole

2022-10-26 20:35 UTC, toppeh commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +      .checkIn(['pressurized_air', 'oxygen', 'helium', 'argon'])
Kyllähän se harmittaa itse kutakin.
Miulla on nyt idea kolmanteen iteraatioon tämän pohjalta

2022-10-26 20:43 UTC, toppeh commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.createTable('fill_cylinder_event', (table) => {
Taulu on nimetty ihan tarkoituksella noin. Ajatuksenani oli, että jokainen pullo täytetään erikseen vaikka ne onkin aina setissä mukana. Mutta jos onkin tuommoisia atomisia tuplapulloja olemassa niin tätä ajatusta täytyy ehkä harkita uudelleen.

2022-10-27 07:53 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.createTable('fill_cylinder_event', (table) => {
Kilautin asiantuntijalle, joka kertoi että 70-luvun jälkeen tuplapullot on ollut yhteydessä toisiinsa niin että ne voi täyttää yhdestä venttiilistä.

2022-10-27 08:06 UTC, ilesoft commented on src/database/migrations/20221025150522_create_fill_event_table.ts
> +  await knex.schema.createTable('fill_cylinder_event', (table) => {
Ja rebeistä taasen otetaan kuulemma pullot erilleen täyttöä varten. => täytettävät "pullosetit" on siis yksittäisiä pulloja eikä meidän tarvi huolehtia siitä  koko laitepaketista tällä tasolla.

2022-10-28 12:13 UTC, kiiskih approved these changes
Tämä on testi

2022-10-29 12:22 UTC, ilesoft approved these changes

2022-10-29 12:26 UTC, merged