Feat/create gas price
Tampereen-Urheilusukeltajat/Blenderi-Backend pull request #53
Opened 2022-12-31 10:38 UTC by Akzuu

Closes #52.

2023-01-02 18:33 UTC, ilesoft requested changes

2023-01-02 18:33 UTC, ilesoft commented on src/types/gas.types.ts
> +});
Jos tää tyyppi kuvaa yhden ostettavan kaasun hintaa jollain aikavälillä niin nimi ei kyllä voi olla `enrichedGas`

ehdotuksia:

*  timedGasPrice
* gasPricing
* Ganada
* joku muu, mikä

2023-01-03 15:18 UTC, Akzuu commented on src/types/gas.types.ts
> +});
Muutetaan `GasWithPricing`

2023-01-15 13:44 UTC, ilesoft approved these changes

2023-01-15 13:56 UTC, merged