Endpoint: GET /user/
Tampereen-Urheilusukeltajat/Blenderi-Backend pull request #8
Opened 2022-10-05 19:39 UTC by toppeh

hakuammuntaa

GET /api/user/user/:userId  - palauttaa yhden käyttäjän, userId on pakollinen  
GET /api/user/user - palauttaa kaikki käyttäjät

2022-10-06 11:27 UTC, toppeh commented on src/routes/users/user.ts
> +  await reply.send(result);
Onko parempi tehdä näin, eli antaa fastifyn validoinnin karsia liiat tiedot pois vai jättää turhat tiedot pois jo tietokantapyynnöstä?

2022-10-06 18:42 UTC, ilesoft commented on src/database/migrations/20221004193118_create_user_table.ts
> +import { Knex } from 'knex';
Tässä PR:ssä ei pitäisi tulla tähän tiedostoon yhtään muutosta. Tee vaikka rebase mainiin niin saat sen sieltä käyttöön.

2022-10-06 18:42 UTC, ilesoft commented on src/types/user.types.ts
> +  blender: Type.Boolean(),
isAdmin ja isBlender niinkuin tietokannassakin nyt on

2022-10-06 18:42 UTC, ilesoft commented on src/types/user.types.ts
> +  blender: Type.Boolean(),
isAdmin ja isBlender

2022-10-06 18:42 UTC, ilesoft commented on src/types/user.types.ts
> +  password_hash: Type.String(),
Jätettäiskö snake_case sinne tietokannan puolelle? Tästä voidaan olla toki eri mieltä.

2022-10-06 18:42 UTC, ilesoft commented on src/types/user.types.ts
> +  id: Type.Number(),
Ei ole enään numero vaan uuid
```suggestion
  id: Type.String(),
```

2022-10-06 18:42 UTC, ilesoft commented on src/routes/users/createuser.ts
> +};
Tää taitaisi kuulua tuonne toiseen PR:ään
https://github.com/Tampereen-Urheilusukeltajat/Blenderi-Backend/pull/6

2022-10-06 18:42 UTC, ilesoft commented on src/routes/users/readuser.ts
> +    .first('email', 'forename', 'surname', 'admin', 'blender');
```suggestion
    .first('email', 'forename', 'surname', 'is_admin', 'is_blender');
```

2022-10-06 18:42 UTC, ilesoft commented on src/routes/users/readuser.ts
> +  // TODO: Don't return if user is archived
```suggestion
  // TODO: Don't return if user is archived or deleted
```

2022-10-06 19:47 UTC, ilesoft commented on src/types/user.types.ts
> +});
Tuli mieleen että tää tulee hajoaamaan kahteen eri userResponse tyyppiin koska admineiden pitää saada tietoa poistetuista käyttäjistä sisältäen tiedon poistamisen ajankohdasta.

Voitanee tehdä vasta myöhemmin.

2022-10-07 05:51 UTC, Akzuu commented on src/types/user.types.ts
> +});
Joo mietitään sitä arkistointia vasta myöhemmin. Menee omalla tiketillä

2022-10-07 12:05 UTC, toppeh commented on src/routes/users/readUser.ts
> +    throw new Error('User was not found');
En tiedä mikä on oikea tapa palauttaa error tässä

2022-10-07 14:10 UTC, ilesoft commented on src/routes/users/readUser.ts
> +    throw new Error('User was not found');
`reply.code(404);` tms

2022-10-07 14:43 UTC, Akzuu commented on src/routes/users/readUser.ts
> +    throw new Error('User was not found');
Teen noiden errorien handlaykseen jonkun kivan apufunkkarin jossain kohtaa

2022-10-07 14:48 UTC, Akzuu requested changes

2022-10-07 14:48 UTC, Akzuu commented on src/routes/users/readUser.ts
> +import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
Even though it C(READ)UD, I would name this getUser

2022-10-07 14:48 UTC, Akzuu commented on src/routes/users/readUser.ts
> +  description: 'Search for an user with given id',
Are we searching for user though? Is this searching? 

I would rather use "Get user with the given id"

2022-10-07 14:48 UTC, Akzuu commented on src/routes/users/readUser.ts
> +    throw new Error('User was not found');
Mut laita tähän vaan nyt reply.code(404).send({ error objekti })

2022-10-07 14:48 UTC, Akzuu commented on src/routes/users/readUser.ts
> +};
Splittaisin vielä näkin reitit omiksi tiedostoikseen.

getUser.ts
getUsers.ts

2022-10-09 19:00 UTC, Akzuu approved these changes

2022-10-10 11:16 UTC, merged